version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install -g aws-cdk
      - cd infrastructure
      - npm install
      - cd ..
      
  pre_build:
    commands:
      - echo Running pre-build checks...
      - cd infrastructure
      - echo Validate CDK app...
      - cdk doctor
      - echo Linting code...
      - npm run lint || echo "No lint script found, skipping..."
      
  build:
    commands:
      - echo Starting build phase...
      - echo Synthesizing CloudFormation template...
      - cdk synth
      - echo Running security checks...
      - echo "Security checks would run here in a production pipeline"
      # Example security check tools you could add:
      # - npm install -g cfn-nag
      # - cfn-nag-scan --input-path ./cdk.out/*.template.json
      
  post_build:
    commands:
      - echo Build phase completed successfully!
      - echo Preparing deployment artifacts...
      - mkdir -p artifacts
      - cp -r cdk.out/* artifacts/
      - cp package.json artifacts/
      - cp package-lock.json artifacts/
      - cd ..
      - echo Build completed on `date`
      
artifacts:
  base-directory: 'infrastructure/artifacts'
  files:
    - '**/*'
  discard-paths: no

cache:
  paths:
    - 'infrastructure/node_modules/**/*'

reports:
  test-reports:
    files:
      - 'infrastructure/test-report.xml'
    file-format: 'JUNITXML'
    base-directory: '.'
    discard-paths: no
